export const warningSigns = [
  { codes: ["501", "502"], caption: "Junction ahead controlled by a STOP sign", group: "1" },
  { codes: ["501", "503"], caption: "Junction ahead controlled by a GIVE WAY sign", group: "1" },
	
  { codes: ["504.1"], caption: "Crossroads ahead", group: "2" },
  { codes: ["504.1A"], caption: "Crossroads ahead (alternative design)", group: "2" },
  { codes: ["505.1"], caption: "T-junction ahead", group: "2" },
  { codes: ["506.1"], caption: "Side road ahead ", group: "2" },
  { codes: ["506.1A"], caption: "Side road ahead (alternative design)", group: "2" },
  { codes: ["507.1"], caption: "Staggered junction ahead", group: "2" },
  { codes: ["507.1A"], caption: "Staggered junction ahead (alternative design)", group: "2" },
  { codes: ["508.1"], caption: "Traffic merging from left ahead", group: "2" },
  { codes: ["509.1"], caption: "Traffic merging onto main carriageway ahead", group: "2" },
  { codes: ["510"], caption: "Roundabout ahead", group: "2" },
	
  { codes: ["512"], caption: "Bend ahead", group: "3" },
  { codes: ["512.4"], caption: "Hairpin bend ahead", group: "3" },
  { codes: ["512.1"], caption: "Junction on the outside of a bend ahead", group: "3" },
  { codes: ["512.2"], caption: "Junction on the inside of a bend ahead", group: "3" },
  { codes: ["512.3"], caption: "Crossroads on a bend ahead", group: "3" },
  { codes: ["513"], caption: "Double bend ahead (first to the left)", group: "3" },
  { codes: ["513R", "570"], caption: "Series of bends for distance shown (first to the right)", group: "3" },
  { codes: ["515"], caption: "Sharp deviation of route to the left", group: "3" },
  { codes: ["515.1"], caption: "Sharp deviation of route to the left (Alternative design)", group: "3" },
  { codes: ["512.1", "513.1"], caption: "Adverse camber on a j-unction on the outside of a bend", group: "3" },
  { codes: ["513.1A"], caption: "Risk of lorries overturning on a bend to the left", group: "3" },
  { codes: ["511"], caption: "Reduction in speed necessary ahead", group: "3" },
  { codes: ["504.1", "511A"], caption: "Warning of large and heavy works vehicles crossing the road ahead", group: "3" },
  { codes: ["516"], caption: "Road narrows on both sides ahead", group: "3" },
  { codes: ["517"], caption: "Road narrows on one sides ahead", group: "3" },
  
  { codes: ["518"], caption: "Single file traffic", group: "4" },
  { codes: ["519"], caption: "Single track road", group: "4" },
  { codes: ["575"], caption: "Oncoming vehicles likely to be in the middle of the road", group: "4" },
  
  { codes: ["520"], caption: "Dual carriageway ends", group: "5" },
  { codes: ["521"], caption: "Two-way traffic", group: "5" },
  { codes: ["522"], caption: "Two-way traffic across the route", group: "5" },
  { codes: ["523.1"], caption: "Steep hill downwards (10% = 1:10)", group: "5" },
  { codes: ["524.1"], caption: "Steep hill upwards (20% = 1:5)", group: "5" },
  { codes: ["528"], caption: "Hump bridge", group: "5" },
	
  { codes: ["525"], caption: "Drivers should select a low gear to navigate a steep hill or bend ahead", group: "6" },
  { codes: ["526"], caption: "Drivers should keep in a low gear while navigating a steep hill or bend ahead", group: "6" },
  { codes: ["527"], caption: "Distance over which a low gear should be selected to navigate a steep hill", group: "6" },

  { codes: ["773"],caption: `<a href="/pages/light-signals.html">Light signals</a> found at swing or lifting bridges, airfields, or level crossings.`, group: "7"},
  { codes: ["773A"],caption: `<a href="/pages/light-signals.html">Light signals</a> found at swing or lifting bridges, airfields, or level crossings. (Alternative design)`, group: "7"},
  { codes: ["529"],caption: "Swing or lifting bridge ahead", group: "7"},
  { codes: ["529.1"],caption: "Tunnel ahead", group: "7"},
  { codes: ["530", "530M"],caption: "Available headroom at an obstruction", group: "7"},
  { codes: ["530", "530M", "530.1"],caption: "Available headroom at an overhanging building", group: "7"},
  { codes: ["531.1", "531.1M", "531.2"],caption: "Drivers of high vehicles should use the centre of the road to pass an arch bridge safely", group: "7"},
  { codes: ["543"],caption: "Traffic signals ahead", group: "7"},
  { codes: ["543", "543.1A"],caption: "Traffic signals that only operate during certain times of the day", group: "7"},
  { codes: ["543", "543.1B"],caption: "Traffic signals that only operate during the peak hours of the day", group: "7"},
  { codes: ["543", "547.8"],caption: "Pedestrian crossing governed by traffic signals on a road hump ahead", group: "7"},
  { codes: ["545"],caption: "Children likely to be in the road ahead", group: "7"},
  { codes: ["545", "546"],caption: "Children likely to be going to or from school ahead", group: "7"},
  { codes: ["545", "547.1"],caption: "School crossing patrol operates ahead", group: "7"},
  { codes: ["545", "547.2"],caption: "Children likely to be going to or from a playground ahead", group: "7"},
  { codes: ["545", "547.7"],caption: "Disabled Children likely to be in the road ahead", group: "7"},
  { codes: ["545", "546", "4004"],caption: "Children likely to be in the road when lights flash", group: "7"},
  { codes: ["544"],caption: "Zebra crossing ahead", group: "7"},
  { codes: ["544", "547.8"],caption: "Zebra crossing on a road hump ahead", group: "7"},
  { codes: ["544.1"],caption: "Pedestrians in road ahead", group: "7"},
  { codes: ["544.1", "547.3"],caption: "Pedestrians in road ahead for distance shown", group: "7"},
  { codes: ["544.1", "546A", "4004"],caption: "Pedestrians in road ahead to attend a funeral", group: "7"},
  { codes: ["544.2"],caption: "Elderly or frail pedestrians in road", group: "7"},
  { codes: ["544.2", "547.4"],caption: "Elderly pedestrians in road ('Elderly' may be varied to 'Disabled' or 'Blind')", group: "7"},
	
	
  { codes: ["548"],caption: "Cattle", group: "7"},
  { codes: ["549"],caption: "Sheep", group: "7"},
  { codes: ["550"],caption: "Wild horses or ponies", group: "7"},
  { codes: ["550.1"],caption: "Accompanied or ridden horses or ponies", group: "7"},
  { codes: ["550.2"],caption: "Horse-drawn vehicles likely to be in the road ahead", group: "7"},
  { codes: ["550.3"],caption: "Horse trams likely to be in the road ahead", group: "7"},
  { codes: ["551"],caption: "Wild animals ahead", group: "7"},
  { codes: ["551.1"],caption: "Wild migratory toads ahead", group: "7"},
  { codes: ["551.2"],caption: "Wild fowl ahead", group: "7"},
  { codes: ["551.3"],caption: "Wild small animals ahead", group: "7"},
  { codes: ["552"],caption: "Cattle grid ahead", group: "7"},
  { codes: ["553.1", "553.3"],caption: "Agricultural vehicles in road ahead", group: "7"},
  { codes: ["553.1", "553.3C"],caption: "Tractors turning in the road ahead", group: "7"},
  { codes: ["553.1", "553.3B"],caption: "Wide vehicles in road ahead", group: "7"},
	
  
  { codes: ["554A"],caption: "Signs can warn of a ford...", group: "7"},
  { codes: ["554B"],caption: "...flood...", group: "7"},
  { codes: ["554C"],caption: "...a gate...", group: "7"},
  { codes: ["554D", "570"],caption: "...or a series of gates for the distance shown", group: "7"},
  { codes: ["554.1"],caption: "Try brakes after a ford or large body of water", group: "7"},
  { codes: ["554.1", "525","817.2"],caption: "Try brakes before descending a steep hill", group: "7"},
  { codes: ["554.2", "554.3"],caption: "Risk of ice or snowdrifts", group: "7"},
  { codes: ["555"],caption: "Quayside or riverbank", group: "7"},
  { codes: ["555.1"],caption: "Watercourse alongside the road", group: "7"},
  { codes: ["556.1", "556.2"],caption: "Soft verges for distance shown", group: "7"},
  { codes: ["556"],caption: "Uneven road ahead", group: "7"},
  { codes: ["557"],caption: "Slippery road surface ahead", group: "7"},
  { codes: ["557.1", "557.2"],caption: "Road humps for distance shown", group: "7"},
  { codes: ["557.1", "557.3"],caption: "Road humps for distance in direction shown", group: "7"},
  { codes: ["557.1", "557.4"],caption: "Road humps in the distance and in the direction shown", group: "7"},
  { codes: ["558"],caption: "Low flying aircraft or sudden aircraft noise ahead", group: "7"},
  { codes: ["558", "558.1"],caption: "Low flying gliders ahead", group: "7"},
  { codes: ["558.2"],caption: "Low flying helicopter or sudden helicopter noise ahead", group: "7"},
  { codes: ["559"],caption: "Risk of falling or fallen rocks ahead", group: "7"},
  { codes: ["581", "570"],caption: "Risk of high winds for the distance shown", group: "7"},
  { codes: ["582"],caption: "Slow military vehicles in the road ahead", group: "7"},
  { codes: ["583", "583.1"],caption: "Slow moving vehicles on an incline for distance shown", group: "7"},
  { codes: ["584", "584.1"],caption: "Queues likely ahead", group: "7"},
  { codes: ["560"],caption: "Markers used at the side of the road to indicate a hazard or obstruction. (The red color may varied to be yellow or white)", group: "7"},
	
  
  { codes: ["562", "563A"],caption: "", group: "8"},
  { codes: ["562", "563B"],caption: "", group: "8"},
  { codes: ["562", "563C"],caption: "", group: "8"},
  { codes: ["562", "563D"],caption: "", group: "8"},
  { codes: ["562", "563E"],caption: "", group: "8"},
  { codes: ["562", "563F"],caption: "", group: "8"},
  { codes: ["562", "563G"],caption: "", group: "8"},
	
		
];

window.warningSigns = warningSigns;
